# Create image for Test/QA with monitoring by SeaLights

# Base image was created via this Dockerfile:
# https://github.com/oracle/docker-images/blob/main/OracleJava/8/Dockerfile
FROM        oracle/jdk:18

# Base dir for app and SeaLights libs
ENV         LIBS_DIR="/usr/local/lib"

# Add application jar
COPY        build/libs/* ${LIBS_DIR}/
EXPOSE      8091

ENTRYPOINT ["java", "-jar", "/usr/local/lib/rest-calculator-0.2.0-SNAPSHOT.jar", "com.slsamples.gradle.java.springboot.Application"]
